name: Charmatch test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  install:
    name: Install
    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler: [ 'ocaml-variants.5.3.0+BER' ]
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - name: Install
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build -p charmatch

      - name: Test
        run: opam exec -- dune exec test/charmatch_tests.exe --  -ci true
